dictionaries = [
    "en_us",
    "ru",
]
words = [
    "bing",
    "bluesky",
    "codeberg",
    "fediverse",
    "gotosocial",
    "homebrew",
    "inkscape",
    "izzy",
    "jetpack",
    "kool",
    "kooltechtricks",
    "lemmy",
    "misskey",
    "neocities",
    "neowiki",
    "obtainium",
    "pacman",
    "pagefind",
    "piefed",
    "tauri",
    "webassembly",
    "yandex",
    "автообновлений",
    "автообновления",
    "автообновлениями",
    "аналитикой",
    "анонимизировать",
    "багов",
    "брендинг",
    "википедии",
    "википедию",
    "википедия",
    "заархивирован",
    "коллаборативный",
    "коммитов",
    "контрибьюторов",
    "контрибьюторы",
    "кэшируются",
    "лого",
    "маскот",
    "медиа",
    "мессенджере",
    "мессенджеров",
    "микроблога",
    "многострочных",
    "переадресации",
    "поддомене",
    "предпросмотр",
    "предпросмотре",
    "пригождается",
    "приоритетнее",
    "приоритизировать",
    "проприетарное",
    "ребрендинга",
    "репозиториев",
    "репозитории",
    "репозиторий",
    "репозитория",
    "репозиториями",
    "рефакторинг",
    "сабреддита",
    "сгенерирован",
    "сгенерированному",
    "сгенерированные",
    "сгенерированный",
    "сгенерировать",
    "сервисов",
    "сервисы",
    "скриншот",
    "скриншотов",
    "скриншоты",
    "слоп",
    "таргетированную",
    "трекер",
    "форки",
    "фреймворки",
    "фронтенд",
    "фронтенде",
    "чатам",
    "чаты",
    "эмодзи",
    "яндекс",
    "яндекса",
]
flag_words = ["оффлайн"]
include_paths = ["content/**/*.md"]
ignore_patterns = [
    "`[^`]*`",
    "«.*»",
    "[A-ZА-ЯЁ]+",
    "[A-Z]{2,}[a-z]+",
]
min_word_length = 4
